export const CTI_ENGINE_CONFIG = {
  CONVERSATION_TOPIC_MEDIUM_SIMILARITY_LOWER_THRESHOLD: 0.4,
  CONVERSATION_TOPIC_MEDIUM_SIMILARITY_UPPER_THRESHOLD: 0.6,
  CONVERSATION_TOPIC_SCORE_HALF_LIFE_HOURS: 72,
  CONVERSATION_TOPIC_SCORE_HYSTERESIS_PERCENTAGE: 0.15,
  CONVERSATION_TOPIC_MINIMUM_EVIDENCE_THRESHOLD: 3,
  MAX_TOPIC_EMBEDDING_TIMEOUT_MS: 2000,
  CTI_LLM_MODEL: "gpt-5.4-nano",
  CTI_LLM_MAX_TOPICS: 5,
  CTI_LLM_REASONING: "none" as const,
  CTI_LLM_TIMEOUT_MS: 20_000,
} as const;
