export const SCORING_CONFIG = {
  NORMALIZER: {
    TYPE: "SIGMOID",
    K: 0.05,
    MIDPOINT: 50,
  },

  SHOULD_EMBED_THRESHOLD: 0.65,

  RULES: {
    HEUR_MSG_LENGTH: {
      ENABLED: true,
      WEIGHT: 10,
      MIN_WORDS: 10,
    },

    HEUR_MSG_TECH_TERMS: {
      ENABLED: true,
      WEIGHT: 10,
      KEYWORDS: [
        "architecture",
        "architectural",
        "system",
        "module",
        "component",
        "service",
        "microservice",
        "monolith",
        "layer",
        "pipeline",
        "workflow",
        "process",
        "orchestration",
        "integration",
        "frontend",
        "backend",
        "fullstack",
        "ui",
        "ux",
        "responsive",
        "layout",
        "design system",
        "wireframe",
        "prototype",
        "state",
        "props",
        "hook",
        "render",
        "hydration",
        "routing",
        "html",
        "css",
        "scss",
        "sass",
        "javascript",
        "typescript",
        "node",
        "react",
        "vue",
        "angular",
        "nextjs",
        "nuxt",
        "svelte",
        "tailwind",
        "api",
        "rest",
        "graphql",
        "endpoint",
        "request",
        "response",
        "payload",
        "header",
        "body",
        "query",
        "mutation",
        "webhook",
        "sdk",
        "database",
        "db",
        "sql",
        "nosql",
        "postgres",
        "postgresql",
        "mysql",
        "sqlite",
        "mongodb",
        "redis",
        "schema",
        "table",
        "column",
        "index",
        "migration",
        "constraint",
        "foreign key",
        "primary key",
        "transaction",
        "embedding",
        "embeddings",
        "vector",
        "pgvector",
        "llm",
        "prompt",
        "completion",
        "inference",
        "semantic",
        "similarity",
        "token",
        "context window",
        "rag",
        "docker",
        "container",
        "kubernetes",
        "cluster",
        "server",
        "client",
        "cdn",
        "cache",
        "proxy",
        "load balancer",
        "nginx",
        "cloudflare",
        "vercel",
        "netlify",
        "supabase",
        "aws",
        "azure",
        "gcp",
        "deployment",
        "deploy",
        "build",
        "release",
        "ci",
        "cd",
        "environment",
        "development",
        "staging",
        "production",
        "rollback",
        "artifact",
        "git",
        "github",
        "branch",
        "commit",
        "merge",
        "pull request",
        "pr",
        "rebase",
        "conflict",
        "tag",
        "bug",
        "issue",
        "error",
        "exception",
        "crash",
        "failure",
        "fix",
        "hotfix",
        "regression",
        "debug",
        "logging",
        "trace",
        "stack trace",
        "test",
        "testing",
        "unit test",
        "integration test",
        "e2e",
        "playwright",
        "cypress",
        "jest",
        "coverage",
        "mock",
        "stub",
        "authentication",
        "authorization",
        "oauth",
        "jwt",
        "session",
        "cookie",
        "csrf",
        "xss",
        "cors",
        "permission",
        "role",
        "rls",
        "encryption",
        "optimization",
        "performance",
        "latency",
        "throughput",
        "memory",
        "cpu",
        "bandwidth",
        "profiling",
        "requirement",
        "specification",
        "acceptance criteria",
        "user story",
        "epic",
        "task",
        "ticket",
        "backlog",
        "roadmap",
        "milestone",
        "priority",
        "estimate",
        "scope",
        "dependency",
        "blocker",
        "risk",
        "scrum",
        "kanban",
        "sprint",
        "retrospective",
        "standup",
        "planning",
        "refinement",
        "velocity",
        "brainstorm",
        "proposal",
        "concept",
        "idea",
        "hypothesis",
        "experiment",
        "validation",
        "assumption",
        "tradeoff",
        "alternative",
        "approach",
        "strategy",
        "analytics",
        "tracking",
        "metric",
        "kpi",
        "event",
        "dimension",
        "attribute",
        "dashboard",
        "report",
        "json",
        "yaml",
        "xml",
        "csv",
        "markdown",
        "algorithm",
        "heuristic",
        "parameter",
        "configuration",
        "implementation",
        "interface",
        "abstraction",
        "inheritance",
        "composition",
        "refactor",
        "normalization",
        "serialization",
        "deserialization",
      ],
    },

    HEUR_MSG_EXPLANATION_WORDS: {
      ENABLED: true,
      WEIGHT: 8,
      WORDS: [
        "because",
        "since",
        "therefore",
        "thus",
        "hence",
        "so",
        "as a result",
        "consequently",
        "for this reason",
        "which means",
        "that means",
        "meaning",
        "in other words",
        "in order to",
        "so that",
        "thereby",
        "this allows",
        "this enables",
        "this prevents",
        "this avoids",
        "this ensures",
        "the reason is",
        "the idea is",
        "the goal is",
        "the purpose is",
        "this is why",
      ],
    },

    HEUR_MSG_LISTS: {
      ENABLED: true,
      WEIGHT: 12,
      MIN_ITEMS: 3,
    },

    HEUR_MSG_BULLET_LIST: {
      ENABLED: true,
      WEIGHT: 20,
      MIN_ITEMS: 3,
    },

    HEUR_MSG_URLS: {
      ENABLED: true,
      WEIGHT: 5,
    },

    HEUR_MSG_CODE: {
      ENABLED: true,
      WEIGHT: 10,
    },

    HEUR_MSG_CODE_BLOCK: {
      ENABLED: true,
      WEIGHT: 30,
      DETECT_FENCED_CODE: true,
    },

    HEUR_MSG_COMMANDS: {
      ENABLED: true,
      WEIGHT: 30,
      PATTERNS: [
        /^create\b/i,
        /^add\b/i,
        /^build\b/i,
        /^generate\b/i,
        /^implement\b/i,
        /^introduce\b/i,
        /^define\b/i,
        /^initialize\b/i,
        /^update\b/i,
        /^change\b/i,
        /^modify\b/i,
        /^adjust\b/i,
        /^refactor\b/i,
        /^rewrite\b/i,
        /^replace\b/i,
        /^rename\b/i,
        /^convert\b/i,
        /^migrate\b/i,
        /^simplify\b/i,
        /^improve\b/i,
        /^optimi[sz]e\b/i,
        /^move\b/i,
        /^extract\b/i,
        /^split\b/i,
        /^merge\b/i,
        /^group\b/i,
        /^reorganize\b/i,
        /^relocate\b/i,
        /^store\b/i,
        /^save\b/i,
        /^persist\b/i,
        /^cache\b/i,
        /^delete\b/i,
        /^remove\b/i,
        /^drop\b/i,
        /^discard\b/i,
        /^clean\b/i,
        /^use\b/i,
        /^prefer\b/i,
        /^choose\b/i,
        /^keep\b/i,
        /^adopt\b/i,
        /^ignore\b/i,
        /^avoid\b/i,
        /^prevent\b/i,
        /^allow\b/i,
        /^forbid\b/i,
        /^enable\b/i,
        /^disable\b/i,
        /^ensure\b/i,
        /^validate\b/i,
        /^let'?s\b/i,
        /^we should\b/i,
        /^we need to\b/i,
        /^we must\b/i,
        /^we can\b/i,
        /^do not\b/i,
        /^don't\b/i,
        /^never\b/i,
        /^always\b/i,
      ],
    },

    HEUR_MSG_DECISIONS: {
      ENABLED: true,
      WEIGHT: 30,
      PATTERNS: [
        /we decided\b/i,
        /decision made\b/i,
        /the decision is\b/i,
        /it was decided\b/i,
        /we agreed on\b/i,
        /we agreed upon\b/i,
        /everyone agreed\b/i,
        /consensus is\b/i,
        /we reached consensus\b/i,
        /we settled on\b/i,
        /we landed on\b/i,
        /we ended up\b/i,
        /we chose\b/i,
        /the chosen\b/i,
        /the selected\b/i,
        /we aligned on\b/i,
        /we are aligned\b/i,
        /we'll\b/i,
        /we will\b/i,
        /going forward\b/i,
        /from now on\b/i,
        /moving forward\b/i,
        /the mvp will\b/i,
        /the first version will\b/i,
        /the implementation will\b/i,
        /in conclusion\b/i,
        /to conclude\b/i,
        /ultimately\b/i,
        /the conclusion is\b/i,
        /resolved\b/i,
        /this settles\b/i,
        /this confirms\b/i,
        /this establishes\b/i,
        /this means we\b/i,
      ],
    },

    HEUR_MSG_NUMBERS: {
      ENABLED: true,
      WEIGHT: 5,
    },

    HEUR_MSG_PROPOSAL: {
      ENABLED: true,
      WEIGHT: 25,
      PATTERNS: [
        /^what if we\b/i,
        /^what if\b/i,
        /^why don't we\b/i,
        /^could we\b/i,
        /^should we\b/i,
        /^would it make sense to\b/i,
        /^does it make sense to\b/i,
        /^how about\b/i,
        /^how would\b/i,
        /^perhaps we could\b/i,
        /^maybe we could\b/i,
        /^maybe we should\b/i,
        /^it might be better to\b/i,
        /^it may be worth\b/i,
        /^it could be useful to\b/i,
        /^i wonder if\b/i,
        /^have we considered\b/i,
        /^has anyone considered\b/i,
        /^an alternative would be\b/i,
        /^another option would be\b/i,
        /^one idea is\b/i,
        /^here's an idea\b/i,
        /^a possible approach\b/i,
        /^one possibility\b/i,
        /^is there a way to\b/i,
        /^can we think of\b/i,
        /^could there be\b/i,
      ],
    },

    HEUR_CONTEXT_QUESTION: {
      ENABLED: true,
      WEIGHT: 25,
      PREVIOUS_MESSAGES: 2,
    },

    HEUR_CONTEXT_SAME_AUTHOR_2: {
      ENABLED: true,
      WEIGHT: 12,
      PREVIOUS_MESSAGES: 2,
    },

    HEUR_CONTEXT_SAME_AUTHOR_4: {
      ENABLED: true,
      WEIGHT: 30,
      PREVIOUS_MESSAGES: 4,
    },
  },
} as const;
