export const SEMANTIC_SEARCH_CONFIG = {
  EMBEDDING_THRESHOLD: 0.75,
  SCORE_WEIGHT_SIMILARITY: 0.8,
  SCORE_WEIGHT_QUALITY: 0.1,
  SCORE_WEIGHT_RECENCY: 0.1,
  RECENCY_HALF_LIFE_DAYS: 180,
} as const;
