export const SEMANTIC_SEARCH_CONFIG = {
  EMBEDDING_THRESHOLD: 0.5,
  SCORE_WEIGHT_SIMILARITY: 0.7,
  SCORE_WEIGHT_QUALITY: 0.15,
  SCORE_WEIGHT_RECENCY: 0.15,
  RECENCY_HALF_LIFE_DAYS: 180,
} as const;
