export const SEMANTIC_SEARCH_CONFIG = {
  MESSAGE_EMBEDDING_THRESHOLD: 0.3,
  MESSAGE_SCORE_WEIGHT_SIMILARITY: 0.7,
  MESSAGE_SCORE_WEIGHT_QUALITY: 0.15,
  MESSAGE_SCORE_WEIGHT_RECENCY: 0.15,
  MESSAGE_RECENCY_HALF_LIFE_DAYS: 180,
  PAGE_EMBEDDING_THRESHOLD: 0.3,
  PAGE_SCORE_WEIGHT_SIMILARITY: 0.85,
  PAGE_SCORE_WEIGHT_RECENCY: 0.15,
  PAGE_RECENCY_HALF_LIFE_DAYS: 180,
} as const;
