export const CANONICAL_TOPIC_ENGINE_CONFIG = {
  CANONICAL_TOPIC_MEDIUM_SIMILARITY_LOWER_THRESHOLD: 0.2,
  CANONICAL_TOPIC_MEDIUM_SIMILARITY_UPPER_THRESHOLD: 0.5,
  CANONICAL_TOPIC_REGENERATION_EVIDENCE_WINDOW: 5,
  CANONICAL_TOPIC_LLM_MODEL: "gpt-5.4-nano",
  CANONICAL_TOPIC_LLM_MAX_CONTEXT_TOPIC_NUMBER: 10,
  CANONICAL_TOPIC_LLM_TIMEOUT_MS: 20_000,
  CANONICAL_TOPIC_LLM_REASONING: "none" as const,
  CANONICAL_TOPIC_EMBEDDING_TIMEOUT_MS: 2_000,
} as const;
