export const PAGE_CHUNK_CONFIG = {
  PAGE_CHUNKING_DEBOUNCE_MS: 5 * 60 * 1000,
  PAGE_CHUNK_REFERENCE_SIZE_TOKENS: 500,
  PAGE_CHUNK_TOLERANCE_SIZE_TOKENS: 150,
  PAGE_CHUNKING_BATCH_SIZE: 20,
  PAGE_EMBEDDING_MODEL: "text-embedding-3-small",
} as const;

export const PAGE_CHUNK_HARD_LIMIT_TOKENS =
  PAGE_CHUNK_CONFIG.PAGE_CHUNK_REFERENCE_SIZE_TOKENS +
  PAGE_CHUNK_CONFIG.PAGE_CHUNK_TOLERANCE_SIZE_TOKENS;

/** Postgres interval for `list_pages_due_for_chunking.p_idle`. */
export const PAGE_CHUNKING_IDLE_INTERVAL = `${PAGE_CHUNK_CONFIG.PAGE_CHUNKING_DEBOUNCE_MS / 1000} seconds`;
