export const PAGE_SEMANTIC_ENGINE_CONFIG = {
  PAGE_SEMANTIC_SNAPSHOT_DIFF_THRESHOLD_TOKENS: 300,
  PAGE_SEMANTIC_LLM_MODEL: "gpt-5.4-nano",
  PAGE_SEMANTIC_LLM_REASONING: "none" as const,
  PAGE_SEMANTIC_LLM_TIMEOUT_MS: 20_000,
  PAGE_SEMANTIC_DEBOUNCE_MS: 5 * 60 * 1000,
  PAGE_SEMANTIC_SWEEP_BATCH_SIZE: 20,
} as const;

/** Postgres interval for `list_pages_due_for_topics.p_idle`. */
export const PAGE_SEMANTIC_IDLE_INTERVAL = `${PAGE_SEMANTIC_ENGINE_CONFIG.PAGE_SEMANTIC_DEBOUNCE_MS / 1000} seconds`;
