/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedGenerateWorkspaceInviteRouteImport } from './routes/_authenticated.generate-workspace-invite'
import { Route as AuthenticatedWWorkspaceIdRouteImport } from './routes/_authenticated.w.$workspaceId'
import { Route as ApiPagesSaveRouteImport } from './routes/api/pages.save'
import { Route as AuthenticatedWWorkspaceIdSettingsRouteImport } from './routes/_authenticated.w.$workspaceId.settings'
import { Route as ApiPublicInternalRunCanonicalTopicsWorkerRouteImport } from './routes/api/public/internal/run-canonical-topics-worker'
import { Route as ApiPublicInternalRunConversationSuggestionWorkerRouteImport } from './routes/api/public/internal/run-conversation-suggestion-worker'
import { Route as ApiPublicInternalRunCtiWorkerRouteImport } from './routes/api/public/internal/run-cti-worker'
import { Route as ApiPublicInternalRunEmbeddingWorkerRouteImport } from './routes/api/public/internal/run-embedding-worker'
import { Route as ApiPublicInternalRunPageChunkingWorkerRouteImport } from './routes/api/public/internal/run-page-chunking-worker'
import { Route as ApiPublicInternalRunPageEmbeddingWorkerRouteImport } from './routes/api/public/internal/run-page-embedding-worker'
import { Route as ApiPublicInternalRunPageSemanticWorkerRouteImport } from './routes/api/public/internal/run-page-semantic-worker'
import { Route as ApiPublicInternalRunPurgeWorkerRouteImport } from './routes/api/public/internal/run-purge-worker'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as AuthenticatedWWorkspaceIdCConversationIdRouteImport } from './routes/_authenticated.w.$workspaceId.c.$conversationId'
import { Route as AuthenticatedWWorkspaceIdPPageIdRouteImport } from './routes/_authenticated.w.$workspaceId.p.$pageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGenerateWorkspaceInviteRoute =
  AuthenticatedGenerateWorkspaceInviteRouteImport.update({
    id: '/generate-workspace-invite',
    path: '/generate-workspace-invite',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceIdRoute =
  AuthenticatedWWorkspaceIdRouteImport.update({
    id: '/w/$workspaceId',
    path: '/w/$workspaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPagesSaveRoute = ApiPagesSaveRouteImport.update({
  id: '/api/pages/save',
  path: '/api/pages/save',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWWorkspaceIdSettingsRoute =
  AuthenticatedWWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWWorkspaceIdRoute,
  } as any)
const ApiPublicInternalRunCanonicalTopicsWorkerRoute =
  ApiPublicInternalRunCanonicalTopicsWorkerRouteImport.update({
    id: '/api/public/internal/run-canonical-topics-worker',
    path: '/api/public/internal/run-canonical-topics-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInternalRunConversationSuggestionWorkerRoute =
  ApiPublicInternalRunConversationSuggestionWorkerRouteImport.update({
    id: '/api/public/internal/run-conversation-suggestion-worker',
    path: '/api/public/internal/run-conversation-suggestion-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInternalRunCtiWorkerRoute =
  ApiPublicInternalRunCtiWorkerRouteImport.update({
    id: '/api/public/internal/run-cti-worker',
    path: '/api/public/internal/run-cti-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInternalRunEmbeddingWorkerRoute =
  ApiPublicInternalRunEmbeddingWorkerRouteImport.update({
    id: '/api/public/internal/run-embedding-worker',
    path: '/api/public/internal/run-embedding-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInternalRunPageChunkingWorkerRoute =
  ApiPublicInternalRunPageChunkingWorkerRouteImport.update({
    id: '/api/public/internal/run-page-chunking-worker',
    path: '/api/public/internal/run-page-chunking-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInternalRunPageEmbeddingWorkerRoute =
  ApiPublicInternalRunPageEmbeddingWorkerRouteImport.update({
    id: '/api/public/internal/run-page-embedding-worker',
    path: '/api/public/internal/run-page-embedding-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInternalRunPageSemanticWorkerRoute =
  ApiPublicInternalRunPageSemanticWorkerRouteImport.update({
    id: '/api/public/internal/run-page-semantic-worker',
    path: '/api/public/internal/run-page-semantic-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInternalRunPurgeWorkerRoute =
  ApiPublicInternalRunPurgeWorkerRouteImport.update({
    id: '/api/public/internal/run-purge-worker',
    path: '/api/public/internal/run-purge-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWWorkspaceIdCConversationIdRoute =
  AuthenticatedWWorkspaceIdCConversationIdRouteImport.update({
    id: '/c/$conversationId',
    path: '/c/$conversationId',
    getParentRoute: () => AuthenticatedWWorkspaceIdRoute,
  } as any)
const AuthenticatedWWorkspaceIdPPageIdRoute =
  AuthenticatedWWorkspaceIdPPageIdRouteImport.update({
    id: '/p/$pageId',
    path: '/p/$pageId',
    getParentRoute: () => AuthenticatedWWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/bootstrap': typeof BootstrapRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/generate-workspace-invite': typeof AuthenticatedGenerateWorkspaceInviteRoute
  '/w/$workspaceId': typeof AuthenticatedWWorkspaceIdRouteWithChildren
  '/api/pages/save': typeof ApiPagesSaveRoute
  '/w/$workspaceId/settings': typeof AuthenticatedWWorkspaceIdSettingsRoute
  '/api/public/internal/run-canonical-topics-worker': typeof ApiPublicInternalRunCanonicalTopicsWorkerRoute
  '/api/public/internal/run-conversation-suggestion-worker': typeof ApiPublicInternalRunConversationSuggestionWorkerRoute
  '/api/public/internal/run-cti-worker': typeof ApiPublicInternalRunCtiWorkerRoute
  '/api/public/internal/run-embedding-worker': typeof ApiPublicInternalRunEmbeddingWorkerRoute
  '/api/public/internal/run-page-chunking-worker': typeof ApiPublicInternalRunPageChunkingWorkerRoute
  '/api/public/internal/run-page-embedding-worker': typeof ApiPublicInternalRunPageEmbeddingWorkerRoute
  '/api/public/internal/run-page-semantic-worker': typeof ApiPublicInternalRunPageSemanticWorkerRoute
  '/api/public/internal/run-purge-worker': typeof ApiPublicInternalRunPurgeWorkerRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/w/$workspaceId/c/$conversationId': typeof AuthenticatedWWorkspaceIdCConversationIdRoute
  '/w/$workspaceId/p/$pageId': typeof AuthenticatedWWorkspaceIdPPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/bootstrap': typeof BootstrapRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/generate-workspace-invite': typeof AuthenticatedGenerateWorkspaceInviteRoute
  '/w/$workspaceId': typeof AuthenticatedWWorkspaceIdRouteWithChildren
  '/api/pages/save': typeof ApiPagesSaveRoute
  '/w/$workspaceId/settings': typeof AuthenticatedWWorkspaceIdSettingsRoute
  '/api/public/internal/run-canonical-topics-worker': typeof ApiPublicInternalRunCanonicalTopicsWorkerRoute
  '/api/public/internal/run-conversation-suggestion-worker': typeof ApiPublicInternalRunConversationSuggestionWorkerRoute
  '/api/public/internal/run-cti-worker': typeof ApiPublicInternalRunCtiWorkerRoute
  '/api/public/internal/run-embedding-worker': typeof ApiPublicInternalRunEmbeddingWorkerRoute
  '/api/public/internal/run-page-chunking-worker': typeof ApiPublicInternalRunPageChunkingWorkerRoute
  '/api/public/internal/run-page-embedding-worker': typeof ApiPublicInternalRunPageEmbeddingWorkerRoute
  '/api/public/internal/run-page-semantic-worker': typeof ApiPublicInternalRunPageSemanticWorkerRoute
  '/api/public/internal/run-purge-worker': typeof ApiPublicInternalRunPurgeWorkerRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/w/$workspaceId/c/$conversationId': typeof AuthenticatedWWorkspaceIdCConversationIdRoute
  '/w/$workspaceId/p/$pageId': typeof AuthenticatedWWorkspaceIdPPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/bootstrap': typeof BootstrapRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/generate-workspace-invite': typeof AuthenticatedGenerateWorkspaceInviteRoute
  '/_authenticated/w/$workspaceId': typeof AuthenticatedWWorkspaceIdRouteWithChildren
  '/api/pages/save': typeof ApiPagesSaveRoute
  '/_authenticated/w/$workspaceId/settings': typeof AuthenticatedWWorkspaceIdSettingsRoute
  '/api/public/internal/run-canonical-topics-worker': typeof ApiPublicInternalRunCanonicalTopicsWorkerRoute
  '/api/public/internal/run-conversation-suggestion-worker': typeof ApiPublicInternalRunConversationSuggestionWorkerRoute
  '/api/public/internal/run-cti-worker': typeof ApiPublicInternalRunCtiWorkerRoute
  '/api/public/internal/run-embedding-worker': typeof ApiPublicInternalRunEmbeddingWorkerRoute
  '/api/public/internal/run-page-chunking-worker': typeof ApiPublicInternalRunPageChunkingWorkerRoute
  '/api/public/internal/run-page-embedding-worker': typeof ApiPublicInternalRunPageEmbeddingWorkerRoute
  '/api/public/internal/run-page-semantic-worker': typeof ApiPublicInternalRunPageSemanticWorkerRoute
  '/api/public/internal/run-purge-worker': typeof ApiPublicInternalRunPurgeWorkerRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/w/$workspaceId/c/$conversationId': typeof AuthenticatedWWorkspaceIdCConversationIdRoute
  '/_authenticated/w/$workspaceId/p/$pageId': typeof AuthenticatedWWorkspaceIdPPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/bootstrap'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/generate-workspace-invite'
    | '/w/$workspaceId'
    | '/api/pages/save'
    | '/w/$workspaceId/settings'
    | '/api/public/internal/run-canonical-topics-worker'
    | '/api/public/internal/run-conversation-suggestion-worker'
    | '/api/public/internal/run-cti-worker'
    | '/api/public/internal/run-embedding-worker'
    | '/api/public/internal/run-page-chunking-worker'
    | '/api/public/internal/run-page-embedding-worker'
    | '/api/public/internal/run-page-semantic-worker'
    | '/api/public/internal/run-purge-worker'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/w/$workspaceId/c/$conversationId'
    | '/w/$workspaceId/p/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/bootstrap'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/generate-workspace-invite'
    | '/w/$workspaceId'
    | '/api/pages/save'
    | '/w/$workspaceId/settings'
    | '/api/public/internal/run-canonical-topics-worker'
    | '/api/public/internal/run-conversation-suggestion-worker'
    | '/api/public/internal/run-cti-worker'
    | '/api/public/internal/run-embedding-worker'
    | '/api/public/internal/run-page-chunking-worker'
    | '/api/public/internal/run-page-embedding-worker'
    | '/api/public/internal/run-page-semantic-worker'
    | '/api/public/internal/run-purge-worker'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/w/$workspaceId/c/$conversationId'
    | '/w/$workspaceId/p/$pageId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/bootstrap'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/generate-workspace-invite'
    | '/_authenticated/w/$workspaceId'
    | '/api/pages/save'
    | '/_authenticated/w/$workspaceId/settings'
    | '/api/public/internal/run-canonical-topics-worker'
    | '/api/public/internal/run-conversation-suggestion-worker'
    | '/api/public/internal/run-cti-worker'
    | '/api/public/internal/run-embedding-worker'
    | '/api/public/internal/run-page-chunking-worker'
    | '/api/public/internal/run-page-embedding-worker'
    | '/api/public/internal/run-page-semantic-worker'
    | '/api/public/internal/run-purge-worker'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/w/$workspaceId/c/$conversationId'
    | '/_authenticated/w/$workspaceId/p/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  BootstrapRoute: typeof BootstrapRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPagesSaveRoute: typeof ApiPagesSaveRoute
  ApiPublicInternalRunCanonicalTopicsWorkerRoute: typeof ApiPublicInternalRunCanonicalTopicsWorkerRoute
  ApiPublicInternalRunConversationSuggestionWorkerRoute: typeof ApiPublicInternalRunConversationSuggestionWorkerRoute
  ApiPublicInternalRunCtiWorkerRoute: typeof ApiPublicInternalRunCtiWorkerRoute
  ApiPublicInternalRunEmbeddingWorkerRoute: typeof ApiPublicInternalRunEmbeddingWorkerRoute
  ApiPublicInternalRunPageChunkingWorkerRoute: typeof ApiPublicInternalRunPageChunkingWorkerRoute
  ApiPublicInternalRunPageEmbeddingWorkerRoute: typeof ApiPublicInternalRunPageEmbeddingWorkerRoute
  ApiPublicInternalRunPageSemanticWorkerRoute: typeof ApiPublicInternalRunPageSemanticWorkerRoute
  ApiPublicInternalRunPurgeWorkerRoute: typeof ApiPublicInternalRunPurgeWorkerRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/generate-workspace-invite': {
      id: '/_authenticated/generate-workspace-invite'
      path: '/generate-workspace-invite'
      fullPath: '/generate-workspace-invite'
      preLoaderRoute: typeof AuthenticatedGenerateWorkspaceInviteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceId': {
      id: '/_authenticated/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/pages/save': {
      id: '/api/pages/save'
      path: '/api/pages/save'
      fullPath: '/api/pages/save'
      preLoaderRoute: typeof ApiPagesSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/w/$workspaceId/settings': {
      id: '/_authenticated/w/$workspaceId/settings'
      path: '/settings'
      fullPath: '/w/$workspaceId/settings'
      preLoaderRoute: typeof AuthenticatedWWorkspaceIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceIdRoute
    }
    '/api/public/internal/run-canonical-topics-worker': {
      id: '/api/public/internal/run-canonical-topics-worker'
      path: '/api/public/internal/run-canonical-topics-worker'
      fullPath: '/api/public/internal/run-canonical-topics-worker'
      preLoaderRoute: typeof ApiPublicInternalRunCanonicalTopicsWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/internal/run-conversation-suggestion-worker': {
      id: '/api/public/internal/run-conversation-suggestion-worker'
      path: '/api/public/internal/run-conversation-suggestion-worker'
      fullPath: '/api/public/internal/run-conversation-suggestion-worker'
      preLoaderRoute: typeof ApiPublicInternalRunConversationSuggestionWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/internal/run-cti-worker': {
      id: '/api/public/internal/run-cti-worker'
      path: '/api/public/internal/run-cti-worker'
      fullPath: '/api/public/internal/run-cti-worker'
      preLoaderRoute: typeof ApiPublicInternalRunCtiWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/internal/run-embedding-worker': {
      id: '/api/public/internal/run-embedding-worker'
      path: '/api/public/internal/run-embedding-worker'
      fullPath: '/api/public/internal/run-embedding-worker'
      preLoaderRoute: typeof ApiPublicInternalRunEmbeddingWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/internal/run-page-chunking-worker': {
      id: '/api/public/internal/run-page-chunking-worker'
      path: '/api/public/internal/run-page-chunking-worker'
      fullPath: '/api/public/internal/run-page-chunking-worker'
      preLoaderRoute: typeof ApiPublicInternalRunPageChunkingWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/internal/run-page-embedding-worker': {
      id: '/api/public/internal/run-page-embedding-worker'
      path: '/api/public/internal/run-page-embedding-worker'
      fullPath: '/api/public/internal/run-page-embedding-worker'
      preLoaderRoute: typeof ApiPublicInternalRunPageEmbeddingWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/internal/run-page-semantic-worker': {
      id: '/api/public/internal/run-page-semantic-worker'
      path: '/api/public/internal/run-page-semantic-worker'
      fullPath: '/api/public/internal/run-page-semantic-worker'
      preLoaderRoute: typeof ApiPublicInternalRunPageSemanticWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/internal/run-purge-worker': {
      id: '/api/public/internal/run-purge-worker'
      path: '/api/public/internal/run-purge-worker'
      fullPath: '/api/public/internal/run-purge-worker'
      preLoaderRoute: typeof ApiPublicInternalRunPurgeWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/w/$workspaceId/c/$conversationId': {
      id: '/_authenticated/w/$workspaceId/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/w/$workspaceId/c/$conversationId'
      preLoaderRoute: typeof AuthenticatedWWorkspaceIdCConversationIdRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceIdRoute
    }
    '/_authenticated/w/$workspaceId/p/$pageId': {
      id: '/_authenticated/w/$workspaceId/p/$pageId'
      path: '/p/$pageId'
      fullPath: '/w/$workspaceId/p/$pageId'
      preLoaderRoute: typeof AuthenticatedWWorkspaceIdPPageIdRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceIdRoute
    }
  }
}

interface AuthenticatedWWorkspaceIdRouteChildren {
  AuthenticatedWWorkspaceIdSettingsRoute: typeof AuthenticatedWWorkspaceIdSettingsRoute
  AuthenticatedWWorkspaceIdCConversationIdRoute: typeof AuthenticatedWWorkspaceIdCConversationIdRoute
  AuthenticatedWWorkspaceIdPPageIdRoute: typeof AuthenticatedWWorkspaceIdPPageIdRoute
}

const AuthenticatedWWorkspaceIdRouteChildren: AuthenticatedWWorkspaceIdRouteChildren =
  {
    AuthenticatedWWorkspaceIdSettingsRoute:
      AuthenticatedWWorkspaceIdSettingsRoute,
    AuthenticatedWWorkspaceIdCConversationIdRoute:
      AuthenticatedWWorkspaceIdCConversationIdRoute,
    AuthenticatedWWorkspaceIdPPageIdRoute:
      AuthenticatedWWorkspaceIdPPageIdRoute,
  }

const AuthenticatedWWorkspaceIdRouteWithChildren =
  AuthenticatedWWorkspaceIdRoute._addFileChildren(
    AuthenticatedWWorkspaceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGenerateWorkspaceInviteRoute: typeof AuthenticatedGenerateWorkspaceInviteRoute
  AuthenticatedWWorkspaceIdRoute: typeof AuthenticatedWWorkspaceIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGenerateWorkspaceInviteRoute:
    AuthenticatedGenerateWorkspaceInviteRoute,
  AuthenticatedWWorkspaceIdRoute: AuthenticatedWWorkspaceIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  BootstrapRoute: BootstrapRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPagesSaveRoute: ApiPagesSaveRoute,
  ApiPublicInternalRunCanonicalTopicsWorkerRoute:
    ApiPublicInternalRunCanonicalTopicsWorkerRoute,
  ApiPublicInternalRunConversationSuggestionWorkerRoute:
    ApiPublicInternalRunConversationSuggestionWorkerRoute,
  ApiPublicInternalRunCtiWorkerRoute: ApiPublicInternalRunCtiWorkerRoute,
  ApiPublicInternalRunEmbeddingWorkerRoute:
    ApiPublicInternalRunEmbeddingWorkerRoute,
  ApiPublicInternalRunPageChunkingWorkerRoute:
    ApiPublicInternalRunPageChunkingWorkerRoute,
  ApiPublicInternalRunPageEmbeddingWorkerRoute:
    ApiPublicInternalRunPageEmbeddingWorkerRoute,
  ApiPublicInternalRunPageSemanticWorkerRoute:
    ApiPublicInternalRunPageSemanticWorkerRoute,
  ApiPublicInternalRunPurgeWorkerRoute: ApiPublicInternalRunPurgeWorkerRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
