/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRunEmbeddingWorkerRouteImport } from './routes/api/run-embedding-worker'
import { Route as ApiGenerateEmbeddingsRouteImport } from './routes/api/generate-embeddings'
import { Route as ApiPagesSaveRouteImport } from './routes/api/pages.save'
import { Route as AuthenticatedWWorkspaceIdRouteImport } from './routes/_authenticated.w.$workspaceId'
import { Route as ApiPublicInternalRunEmbeddingWorkerRouteImport } from './routes/api/public/internal/run-embedding-worker'
import { Route as AuthenticatedWWorkspaceIdSettingsRouteImport } from './routes/_authenticated.w.$workspaceId.settings'
import { Route as AuthenticatedWWorkspaceIdPPageIdRouteImport } from './routes/_authenticated.w.$workspaceId.p.$pageId'
import { Route as AuthenticatedWWorkspaceIdCConversationIdRouteImport } from './routes/_authenticated.w.$workspaceId.c.$conversationId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunEmbeddingWorkerRoute = ApiRunEmbeddingWorkerRouteImport.update({
  id: '/api/run-embedding-worker',
  path: '/api/run-embedding-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateEmbeddingsRoute = ApiGenerateEmbeddingsRouteImport.update({
  id: '/api/generate-embeddings',
  path: '/api/generate-embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesSaveRoute = ApiPagesSaveRouteImport.update({
  id: '/api/pages/save',
  path: '/api/pages/save',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWWorkspaceIdRoute =
  AuthenticatedWWorkspaceIdRouteImport.update({
    id: '/w/$workspaceId',
    path: '/w/$workspaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicInternalRunEmbeddingWorkerRoute =
  ApiPublicInternalRunEmbeddingWorkerRouteImport.update({
    id: '/api/public/internal/run-embedding-worker',
    path: '/api/public/internal/run-embedding-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWWorkspaceIdSettingsRoute =
  AuthenticatedWWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWWorkspaceIdRoute,
  } as any)
const AuthenticatedWWorkspaceIdPPageIdRoute =
  AuthenticatedWWorkspaceIdPPageIdRouteImport.update({
    id: '/p/$pageId',
    path: '/p/$pageId',
    getParentRoute: () => AuthenticatedWWorkspaceIdRoute,
  } as any)
const AuthenticatedWWorkspaceIdCConversationIdRoute =
  AuthenticatedWWorkspaceIdCConversationIdRouteImport.update({
    id: '/c/$conversationId',
    path: '/c/$conversationId',
    getParentRoute: () => AuthenticatedWWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/bootstrap': typeof BootstrapRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/generate-embeddings': typeof ApiGenerateEmbeddingsRoute
  '/api/run-embedding-worker': typeof ApiRunEmbeddingWorkerRoute
  '/w/$workspaceId': typeof AuthenticatedWWorkspaceIdRouteWithChildren
  '/api/pages/save': typeof ApiPagesSaveRoute
  '/w/$workspaceId/settings': typeof AuthenticatedWWorkspaceIdSettingsRoute
  '/api/public/internal/run-embedding-worker': typeof ApiPublicInternalRunEmbeddingWorkerRoute
  '/w/$workspaceId/c/$conversationId': typeof AuthenticatedWWorkspaceIdCConversationIdRoute
  '/w/$workspaceId/p/$pageId': typeof AuthenticatedWWorkspaceIdPPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/bootstrap': typeof BootstrapRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/generate-embeddings': typeof ApiGenerateEmbeddingsRoute
  '/api/run-embedding-worker': typeof ApiRunEmbeddingWorkerRoute
  '/w/$workspaceId': typeof AuthenticatedWWorkspaceIdRouteWithChildren
  '/api/pages/save': typeof ApiPagesSaveRoute
  '/w/$workspaceId/settings': typeof AuthenticatedWWorkspaceIdSettingsRoute
  '/api/public/internal/run-embedding-worker': typeof ApiPublicInternalRunEmbeddingWorkerRoute
  '/w/$workspaceId/c/$conversationId': typeof AuthenticatedWWorkspaceIdCConversationIdRoute
  '/w/$workspaceId/p/$pageId': typeof AuthenticatedWWorkspaceIdPPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/bootstrap': typeof BootstrapRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/generate-embeddings': typeof ApiGenerateEmbeddingsRoute
  '/api/run-embedding-worker': typeof ApiRunEmbeddingWorkerRoute
  '/_authenticated/w/$workspaceId': typeof AuthenticatedWWorkspaceIdRouteWithChildren
  '/api/pages/save': typeof ApiPagesSaveRoute
  '/_authenticated/w/$workspaceId/settings': typeof AuthenticatedWWorkspaceIdSettingsRoute
  '/api/public/internal/run-embedding-worker': typeof ApiPublicInternalRunEmbeddingWorkerRoute
  '/_authenticated/w/$workspaceId/c/$conversationId': typeof AuthenticatedWWorkspaceIdCConversationIdRoute
  '/_authenticated/w/$workspaceId/p/$pageId': typeof AuthenticatedWWorkspaceIdPPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/bootstrap'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/api/generate-embeddings'
    | '/api/run-embedding-worker'
    | '/w/$workspaceId'
    | '/api/pages/save'
    | '/w/$workspaceId/settings'
    | '/api/public/internal/run-embedding-worker'
    | '/w/$workspaceId/c/$conversationId'
    | '/w/$workspaceId/p/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/bootstrap'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/api/generate-embeddings'
    | '/api/run-embedding-worker'
    | '/w/$workspaceId'
    | '/api/pages/save'
    | '/w/$workspaceId/settings'
    | '/api/public/internal/run-embedding-worker'
    | '/w/$workspaceId/c/$conversationId'
    | '/w/$workspaceId/p/$pageId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/bootstrap'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/api/generate-embeddings'
    | '/api/run-embedding-worker'
    | '/_authenticated/w/$workspaceId'
    | '/api/pages/save'
    | '/_authenticated/w/$workspaceId/settings'
    | '/api/public/internal/run-embedding-worker'
    | '/_authenticated/w/$workspaceId/c/$conversationId'
    | '/_authenticated/w/$workspaceId/p/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  BootstrapRoute: typeof BootstrapRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiGenerateEmbeddingsRoute: typeof ApiGenerateEmbeddingsRoute
  ApiRunEmbeddingWorkerRoute: typeof ApiRunEmbeddingWorkerRoute
  ApiPagesSaveRoute: typeof ApiPagesSaveRoute
  ApiPublicInternalRunEmbeddingWorkerRoute: typeof ApiPublicInternalRunEmbeddingWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-embedding-worker': {
      id: '/api/run-embedding-worker'
      path: '/api/run-embedding-worker'
      fullPath: '/api/run-embedding-worker'
      preLoaderRoute: typeof ApiRunEmbeddingWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-embeddings': {
      id: '/api/generate-embeddings'
      path: '/api/generate-embeddings'
      fullPath: '/api/generate-embeddings'
      preLoaderRoute: typeof ApiGenerateEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/save': {
      id: '/api/pages/save'
      path: '/api/pages/save'
      fullPath: '/api/pages/save'
      preLoaderRoute: typeof ApiPagesSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/w/$workspaceId': {
      id: '/_authenticated/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/internal/run-embedding-worker': {
      id: '/api/public/internal/run-embedding-worker'
      path: '/api/public/internal/run-embedding-worker'
      fullPath: '/api/public/internal/run-embedding-worker'
      preLoaderRoute: typeof ApiPublicInternalRunEmbeddingWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/w/$workspaceId/settings': {
      id: '/_authenticated/w/$workspaceId/settings'
      path: '/settings'
      fullPath: '/w/$workspaceId/settings'
      preLoaderRoute: typeof AuthenticatedWWorkspaceIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceIdRoute
    }
    '/_authenticated/w/$workspaceId/p/$pageId': {
      id: '/_authenticated/w/$workspaceId/p/$pageId'
      path: '/p/$pageId'
      fullPath: '/w/$workspaceId/p/$pageId'
      preLoaderRoute: typeof AuthenticatedWWorkspaceIdPPageIdRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceIdRoute
    }
    '/_authenticated/w/$workspaceId/c/$conversationId': {
      id: '/_authenticated/w/$workspaceId/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/w/$workspaceId/c/$conversationId'
      preLoaderRoute: typeof AuthenticatedWWorkspaceIdCConversationIdRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceIdRoute
    }
  }
}

interface AuthenticatedWWorkspaceIdRouteChildren {
  AuthenticatedWWorkspaceIdSettingsRoute: typeof AuthenticatedWWorkspaceIdSettingsRoute
  AuthenticatedWWorkspaceIdCConversationIdRoute: typeof AuthenticatedWWorkspaceIdCConversationIdRoute
  AuthenticatedWWorkspaceIdPPageIdRoute: typeof AuthenticatedWWorkspaceIdPPageIdRoute
}

const AuthenticatedWWorkspaceIdRouteChildren: AuthenticatedWWorkspaceIdRouteChildren =
  {
    AuthenticatedWWorkspaceIdSettingsRoute:
      AuthenticatedWWorkspaceIdSettingsRoute,
    AuthenticatedWWorkspaceIdCConversationIdRoute:
      AuthenticatedWWorkspaceIdCConversationIdRoute,
    AuthenticatedWWorkspaceIdPPageIdRoute:
      AuthenticatedWWorkspaceIdPPageIdRoute,
  }

const AuthenticatedWWorkspaceIdRouteWithChildren =
  AuthenticatedWWorkspaceIdRoute._addFileChildren(
    AuthenticatedWWorkspaceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWWorkspaceIdRoute: typeof AuthenticatedWWorkspaceIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWWorkspaceIdRoute: AuthenticatedWWorkspaceIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  BootstrapRoute: BootstrapRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiGenerateEmbeddingsRoute: ApiGenerateEmbeddingsRoute,
  ApiRunEmbeddingWorkerRoute: ApiRunEmbeddingWorkerRoute,
  ApiPagesSaveRoute: ApiPagesSaveRoute,
  ApiPublicInternalRunEmbeddingWorkerRoute:
    ApiPublicInternalRunEmbeddingWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
