export const CONVERSATION_SUGGESTION_ENGINE_CONFIG = {
  CONVERSATION_SUGGESTION_LAST_MSG_CONTEXT_WINDOW_MS: 72 * 60 * 60 * 1000,
  CONVERSATION_SUGGESTION_LAST_MSGS_CONTEXT_THRESHOLD: 10,
  CONVERSATION_SUGGESTION_CURRENT_TOPIC_SCORE_THRESHOLD: 0.8,
  CONVERSATION_SUGGESTION_COOLDOWN_MS: 120 * 60 * 60 * 1000,
  CONVERSATION_SUGGESTION_SEARCH_MATCHES_THRESHOLD: 10,
  CONVERSATION_SUGGESTION_SEARCH_SIMILARITY_THRESHOLD: 0.75,
  CONVERSATION_SUGGESTION_LLM_CONFIDENCE_THRESHOLD: 0.85,
  CONVERSATION_SUGGESTION_EXPIRATION_TIME_MS: 48 * 60 * 60 * 1000,
  CONVERSATION_SUGGESTION_DELAY_AFTER_CONVERSATION_REOPEN_MS: 5 * 60 * 1000,
  CONVERSATION_SUGGESTION_BACKOFF_REPEATED_SUGGESTIONS_MS: 14 * 24 * 60 * 60 * 1000,
  CONVERSATION_SUGGESTION_DEBOUNCE_MS: 5 * 60 * 1000,
  CONVERSATION_SUGGESTION_SWEEP_BATCH_SIZE: 20,
  CONVERSATION_SUGGESTION_TOPIC_FOCUS_MARGIN: 0.01,
  CONVERSATION_SUGGESTION_LLM_MODEL: "gpt-5.4-nano",
  CONVERSATION_SUGGESTION_LLM_REASONING: "none" as const,
  CONVERSATION_SUGGESTION_LLM_TIMEOUT_MS: 20_000,
} as const;

function msToPostgresInterval(ms: number): string {
  return `${ms} milliseconds`;
}

/** Postgres interval for `list_conversation_suggestion_jobs_due.p_idle`. */
export const CONVERSATION_SUGGESTION_IDLE_INTERVAL = msToPostgresInterval(
  CONVERSATION_SUGGESTION_ENGINE_CONFIG.CONVERSATION_SUGGESTION_DEBOUNCE_MS,
);

/** Postgres interval for `list_conversation_suggestion_jobs_due.p_cooldown`. */
export const CONVERSATION_SUGGESTION_COOLDOWN_INTERVAL = msToPostgresInterval(
  CONVERSATION_SUGGESTION_ENGINE_CONFIG.CONVERSATION_SUGGESTION_COOLDOWN_MS,
);
